DATALOADER:
  ASPECT_RATIO_GROUPING: false
  SIZE_DIVISIBILITY: 32
DATASETS:
  GENERAL_COPY: 16
  OVERRIDE_CATEGORY:
  - id: 1
    name: arm
  - id: 2
    name: back
  - id: 3
    name: legcap
  - id: 4
    name: seat
  - id: 5
    name: wheel
  PREDEFINED_TEXT: odinw/pothole/category_description.json
  REGISTER:
    train:
      ann_file: eval_results/prompt_tuning/Chair/test_anno.json
      img_dir: eval_results/prompt_tuning/Chair/test_img
    val:
      ann_file: eval_results/prompt_tuning/Chair/test_anno.json
      img_dir: eval_results/prompt_tuning/Chair/test_img
  TEST: ("val",)
  TRAIN: ("train",)
INPUT:
  MAX_SIZE_TEST: 1333
  MAX_SIZE_TRAIN: 1333
  MIN_SIZE_TEST: 800
  MIN_SIZE_TRAIN: 800
MODEL:
  ATSS:
    NUM_CLASSES: 6
  DYHEAD:
    NUM_CLASSES: 6
  FCOS:
    NUM_CLASSES: 6
  ROI_BOX_HEAD:
    NUM_CLASSES: 6
SOLVER:
  CHECKPOINT_PERIOD: 100
  MAX_EPOCH: 12
  WARMUP_ITERS: 0
TEST:
  IMS_PER_BATCH: 8
